# Author: Nuno Aguiar

todo:
- Check if kube dash is deployed
- Setup a kube proxy
- Open browser

ojob:
  daemon      : true
  opacks      :
  - openaf: 20200523
  - Kube
  loadLibs    :
  - kube.js
  catch       : "logErr(exception)"
  logToConsole: true   # to change when finished

jobs:
# ----------
- name: Help
  help: 
    text   : Does stuff. 
    expects: 
    - name: config
      desc: Complete path and filename for a kubeconfig file.

# ------------------------------------
- name: Check if kube dash is deployed
  exec: |
    args.config = _$(args.config, "config").default(void 0);
 
    global.kube = new Kube();
    if (global.kube.getNamespaces(true).map(r => r.Metadata.Name).indexOf("kubernetes-dashboard") >= 0) {
       log("Kube dashboard is deployed.");
    } else {
       throw "Didn't found kube dashboard!";
       // https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.3/aio/deploy/recommended.yaml (as version)
       // apply split ( --- ) -> array
       // io.readFileString("kdash.yaml").split(/\n---/).map(af.fromYAML).map(o => k.apply("kubernetes-dashboard", o))
    }

# ------------------------
- name: Setup a kube proxy
  exec: |
    args.config = _$(args.config, "config").default(void 0);

    $do(() => { $sh((isDef(args.config) ? "export KUBECONFIG=" + args.config + " && " : "") + "kubectl proxy")
                .prefix("kube proxy")
                .get(0); });

# ------------------
- name: Open browser
  exec: |
    var res = openInBrowser("http://127.0.0.1:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/deployment?namespace=default"); 
    if (!res) print("Open a browser to: http://127.0.0.1:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/deployment?namespace=default");
