# Author: Nuno Aguiar

todo:
- Hacker News 

ojob:
  sequential  : true
  opacks      :
  - openaf: 20200523
  catch       : logErr(exception);
  logToConsole: false   # to change when finished

jobs:
# ----------
- name: Help
  help: 
    text   : Does stuff. 
    expects: 
    - name: something
      desc: To do stuff

# ---------
- name: Hacker News
  exec: |
    var fn = h => h.replace(/<.+?>/g, "").replace(/(( |\n)( |\n))+/g, "$1").trim();

    var rss = af.fromXML2Obj($rest().get("http://feeds.feedburner.com/TheHackersNews?format=xml")).rss.channel.item.map(r => ({ title: r.title, description: fn(r.description), date: r.pubDate, link: r.link }));

    ow.oJob.output(rss, args);

