# Author: Nuno Aguiar

todo:
- Install docker

ojob:
  sequential  : true
  opacks      :
  - openaf: 20200523
  catch       : logErr(exception);
  logToConsole: true   # to change when finished

jobs:
# ----------
- name: Help
  help: 
    text   : Tries to install docker on an unix system

# --------------------
- name: Install docker 
  exec: |
    var f = io.createTempFile();
    $rest().get2File(f, "https://get.docker.com");
    $sh("sh " + f)
    .prefix("sh")
    .get(0);
