# Author: Nuno Aguiar
init:
  help: &HELP
    text   : Adds a swapfile on the current linux
    expects: 
    - name   : "size"
      desc   : The size, in GB, of the swapfile
      example: 1GB

todo:
- Add swap

ojob:
  opacks      :
  - openaf: 20210412
  catch       : "ow.oJob.output({ Help: args.init.help }, args); logErr(exception); return false;"
  logToConsole: true   # to change when finished
        

jobs:
# ----------
- name: Help
  help: *HELP

# -----------------------
- name: Add swap commands
  lang: shell
  typeArgs:
    shellPrefix: ('sh')
  exec: |
    sudo dd if=/dev/zero of=/swapfile bs=1024 count={{size}}
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    echo '/swapfile swap swap defaults 0 0' >> /etc/fstab
    
# --------------
- name: Add swap
  to  : Add swap commands
  exec: |
    _$(args.size, "size").$_();

    args.size = Number(args.size) * 1024 * 1024;