# Author            : Nuno Aguiar

init:
  # The port where the rest services will be available
  port  : &PORT   8787
  # Where the pid file will be located
  piddir: &PIDDIR service.pid

ojob:
  daemon      : true
  argsFromEnvs: true
  opacks      :
  - oJob-common
  unique      :
    pidFile     : *PIDDIR
    killPrevious: false
  catch       : |
    sprintErr(exception);

include:
  - oJobRest.yaml

todo:
- name: REST Start Server
  args: |
    ({ port: Number( _$(args.port, "port").default(global.args.init.port) ) })
- name: Prepare Healthz
- name: Prepare html
- name: Prepare default

jobs:
# ----------
- name: Help
  help:
    text   : | 
      Launches a simple service to execute a job with the provided arguments where __ojob is the job to execute.
      Example: 'curl -XPOST http://my.service:8787 -H "Content-Type: application/json" -d "{ \"__ojob\": \"ojob.io/hello/world\" }"'
    expects:
    - name: port
      desc: The port on which to launch the service (defaults to 8787)

# ---------------------
- name: Prepare Healthz
  to  : REST Healthz
  args:
    uri: /healthz
  exec: |
    args.port = Number( _$(args.port, "port").default(global.args.init.port) );

# ------------------
- name: Prepare html
  to  : REST Service
  args:
    uri       : /html
    returnHTML: true
    execGET   : "return ow.server.httpd.reply('', 200, 'text/html', {})"
    execPOST  : |
      try { 
      if (isUnDef(data.__ojob)) return {};
      log("Running '" + stringify(data, void 0, "") + "'...");
      __pm = {};
      oJobRunFile(data.__ojob, merge(data, { __format: "pm" }), genUUID(), void 0, true);
      var res = clone(__pm);

      ow.loadTemplate();
      var c = {};
      if (isDef(res)) {
         if (isDef(res._map))  c = ow.template.html.parseMap(res._map, true);
         if (isDef(res._list)) c = ow.template.html.parseMap(res._list, true);
      }
      
      c.out = c.out.replace(new RegExp("((http|https|ftp)://[a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*))", "gi"), "<a href=\"$1\">$1</a>");
      var html = "<html><style>" + c.css + "</style><body>" + c.out + "</body></html>"; 
 
      return ow.server.httpd.reply(html, 200, 'text/html', {}) 
      } catch(e) { sprintErr(e) }
    execPUT   : "return ow.server.httpd.reply('', 200, 'text/html', {})"
    execDELETE: "return ow.server.httpd.reply('', 200, 'text/html', {})"
  exec: |
    args.port = Number( _$(args.port, "port").default(global.args.init.port) );


# ---------------------
- name: Prepare default
  to  : REST Service
  args:
    uri       : /
    execGET   : "return { a: 1 }"
    execPOST  : |
      if (isUnDef(data.__ojob)) return {};
      log("Running '" + stringify(data, void 0, "") + "'...");
      __pm = {};
      oJobRunFile(data.__ojob, merge(data, { __format: "pm" }), genUUID(), void 0, true);
      var res = clone(__pm);
      if (isDef(res._map)) return res._map;
      if (isDef(res._list)) return res._list;
      if (isDef(res.result)) return { result: res.result };
      return res; 
    execPUT   : "return { }"
    execDELETE: "return { }"
  exec: |
    args.port = Number( _$(args.port, "port").default(global.args.init.port) );
