# Author: Nuno Aguiar

todo:
- Check Windows
- Open Internet Options

ojob:
  opacks      :
  - openaf: 20200523
  catch       : logErr(exception);
  logToConsole: true   # to change when finished
  sequential  : true

jobs:
# ----------
- name: Help
  help: 
    text   : Opens Windows Internet Options 
    # expects: 
    # - name   : something
    #   desc   : To do stuff
    #   example: aValueExample

# -------------------
- name: Check Windows
  exec: |
    ow.loadFormat();
    if (!ow.format.isWindows()) throw "This job is intended only for Windows."

# ---------------------------
- name: Open Internet Options
  exec: |
    $sh("%SYSTEMROOT%/System32/control.exe inetcpl.cpl,,4").exec(0);