# Author: Nuno Aguiar
init:
  help: &HELP
    text   : Adds to the current windows user PATH a specific path or the path to OpenAF
    expects:
    - name   : setPath
      desc   : The path to set for the current windows user (defaults to OpenAF path) 
      example: C:/some/path

todo:
- Get and Set Path

ojob:
  opacks      :
  - openaf     : 20210412
  catch       : "ow.oJob.output({ Help: args.init.help }, args); logErr(exception);"
  logToConsole: true   # to change when finished
  sequential  : true

jobs:
- name: Get and Set Path
  from: 
  - Get Path
  to  :
  - Find Path
  - Set Path

# --------------
- name: Get Path
  lang: powershell
  exec: | 
    $out = (Get-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Environment' -Name PATH)
    $out | ConvertTo-JSON

# --------------
- name: Set Path
  lang: powershell
  exec: |
    Set-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Environment' -Name PATH -Value "{{{newPath}}}"

# ---------------
- name: Find Path
  exec: |
    _$(args.PATH, "PATH").isString().$_("Path not found.");
    var ar = args.PATH.split(";");
    var p = args.setPath || getOpenAFPath();
    var oafPath = p.replace(/\/$/, "").replace(/\//g, "\\");

    if (ar.indexOf(oafPath) < 0) ar.push(oafPath);
    args.newPath = ar.filter(r => r.length > 0).join(";");
