// Author: Nuno Aguiar
help: &HELP
  text   : Provides public IP information from the current internet connection or a provided ip address.
  expects: 
  - name     : ip
    desc     : The ip to look for (e.g. 1.2.3.4)
    mandatory: true
    example  : 8.8.8.8

todo:
- Get public IP info

ojob:
  logToConsole: false
  opacks      :
  - openaf: 20210721

jobs:
# ----------
- name: Help
  help: *HELP

# ------------------------
- name: Get public IP info
  exec: |
    ow.loadNet();
    var info = ow.net.getPublicIP(args.ip);
    ow.oJob.output({ publicIP: info }, args);
